CREATE TABLE ANIME (
    ANIM_ID VARCHAR(30) NOT NULL,
    ANIM_TITLE VARCHAR(250) NOT NULL,
    ANIM_TYPE VARCHAR(10) NOT NULL,
    ANIM_START_DATE DATE,
    ANIM_END_DATE DATE,
    ANIM_SYNOPSIS TEXT,
    ANIM_ANIDB_ID VARCHAR(10)
);

ALTER TABLE ANIME ADD PRIMARY KEY (ANIM_ID);

CREATE TABLE ANIME_EPISODE (
    ANEP_ID VARCHAR(30) NOT NULL,
    ANEP_ANIM_ID VARCHAR(30) NOT NULL,
    ANEP_NUMBER VARCHAR(4) NOT NULL,
    ANEP_TITLE  VARCHAR(250) NOT NULL
);

ALTER TABLE ANIME_EPISODE ADD PRIMARY KEY (ANEP_ID);
CREATE UNIQUE INDEX UN_ANEP_01 ON ANIME_EPISODE (ANEP_ANIM_ID, ANEP_NUMBER);
ALTER TABLE ANIME_EPISODE ADD CONSTRAINT FK_ANEP_ANIM FOREIGN KEY (ANEP_ANIM_ID) REFERENCES ANIME (ANIM_ID);