CREATE TABLE ELEMENT (
    ELEM_ID VARCHAR(30) NOT NULL,
    ELEM_TITLE VARCHAR(250) NOT NULL,
    ELEM_TYPE VARCHAR(10) NOT NULL,
    ELEM_SUBTYPE VARCHAR(10) NOT NULL,
    ELEM_RELEASE_YEAR SMALLINT,
    ELEM_SYNOPSIS TEXT
);

ALTER TABLE ELEMENT ADD PRIMARY KEY (ELEM_ID);
