CREATE TABLE RELATION (
    RELA_ID VARCHAR(30) NOT NULL,
    RELA_ELEM_ID VARCHAR(30) NOT NULL,
    RELA_ELEM_RELATED_ID VARCHAR(30) NOT NULL,
    RELA_TYPE VARCHAR(10) NOT NULL
);

ALTER TABLE RELATION ADD PRIMARY KEY (RELA_ID);
