CREATE TABLE EXTERNAL_SITE (
    EXSI_ID VARCHAR(30) NOT NULL,
    EXSI_CODE VARCHAR(30) NOT NULL,
    EXSI_SITE_NAME VARCHAR(50) NOT NULL,
    EXSI_URL_TEMPLATE VARCHAR(250) NOT NULL
);

ALTER TABLE EXTERNAL_SITE ADD PRIMARY KEY (EXSI_ID);
