CREATE TABLE ANIDB_TITLE (
    ADTI_ID VARCHAR(30) NOT NULL,
    ADTI_AID VARCHAR(10) NOT NULL,
    ADTI_TYPE VARCHAR(1) NOT NULL,
    ADTI_LANG VARCHAR(10) NOT NULL,
    ADTI_TITLE VARCHAR(250) NOT NULL
);

ALTER TABLE ANIDB_TITLE ADD PRIMARY KEY (ADTI_ID);
