CREATE TABLE COLLECTION (
    COLL_ID VARCHAR(30) NOT NULL,
    COLL_NAME VARCHAR(250) NOT NULL
);

ALTER TABLE COLLECTION ADD PRIMARY KEY (COLL_ID);

CREATE TABLE L_ELEMENT_COLLECTION (
    ELEMENT_ID VARCHAR(30) NOT NULL,
    COLLECTION_ID VARCHAR(30) NOT NULL
);

ALTER TABLE L_ELEMENT_COLLECTION ADD PRIMARY KEY (ELEMENT_ID, COLLECTION_ID);