CREATE TABLE PLAYLIST_ITEM (
    PLIT_ID VARCHAR(30) NOT NULL,
    PLIT_ELEM_ID VARCHAR(30) NOT NULL,
    PLIT_STATUS VARCHAR(1) NOT NULL,
    PLIT_START_DATE DATE,
    PLIT_END_DATE DATE,
    PLIT_CURRENT_EPISODE SMALLINT,
    PLIT_LAST_UPDATE DATETIME
);

ALTER TABLE PLAYLIST_ITEM ADD PRIMARY KEY (PLIT_ID);

CREATE TABLE PLAYLIST_ITEM_USER (
    PLIU_PLIT_ID VARCHAR(30) NOT NULL,
    PLIU_USER_ID VARCHAR(30) NOT NULL
);
